### ISSUE TITLE
Enhance & Bugfix URL to listings

### ISSUE THREAD

**Issue by hscstudio** [pactmeshdotcom/web#4]
Listings should http://www.pactmesh.com/iphoneseller/listings of http://www.pactmesh.com/user/iphoneseller/listings

And bug in ListingController.. cannot get listing by username

**Comment by hscstudio** [comment]
edit /pactmesh/frontend/config/main.php
```php
'user/<username:\w+>/listings' => 'listings/user',
```
Edit actionUser in /pactmesh/frontend/controllers/ListingsController.php
```php
            $user = User::find()->where(['username'=>$username])->one();
            if ($user === null) {
                throw new NotFoundHttpException();
            }
```
Change URL my-listings in /pactmesh/frontend/views/layouts/main.php to user/username/listings
```php
['label' => 'My Listings', 'url' => ['/user/' . Yii::$app->user->identity->username . '/listings']],
```

**Comment by hscstudio** [comment]
It's done, please check @pactmesh

**Comment by pactmesher** [comment]
yes done
